[package]
name = "usvg-cli"
version = "0.9.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
keywords = ["svg"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG simplification tool."
categories = ["multimedia::images"]
workspace = "../../"

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
fern = "=0.5.8" # fixed version without chrono
log = "0.4"
pico-args = "0.2"
usvg = { version = "0.9", path = "../../usvg", default-features = false }

[features]
default = ["text"]
text = ["usvg/text"]

[[bin]]
name = "usvg"
path = "src/main.rs"
