[package]
name = "rendersvg"
version = "0.9.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
edition = "2018"
workspace = "../../"

[dependencies]
fern = "=0.5.8" # fixed version without chrono
log = "0.4"
pico-args = "0.2"
resvg = { path = "../../", default-features = false }

[features]
default = ["text"]
cairo-backend = ["resvg/cairo-backend"]
qt-backend = ["resvg/qt-backend"]
raqote-backend = ["resvg/raqote-backend"]
skia-backend = ["resvg/skia-backend"]
text = ["resvg/text"]
