dist: xenial
language: rust
rust:
  - stable
install:
  - ./testing-tools/ci-install.sh
  # prepare custom Qt
  - if [ "$RESVG_QT_BACKEND" = true ]; then
        source /opt/qt56/bin/qt56-env.sh;
    fi
script: ./testing-tools/run-tests.py
env:
  matrix:
    - RESVG_QT_BACKEND=true
    - RESVG_CAIRO_BACKEND=true
    - RESVG_RAQOTE_BACKEND=true
    - RESVG_SKIA_BACKEND=true
    - RESVG_SKIA_SAFE_BACKEND=true
    - USVG_TESTING=true
