[package]
name = "resvg"
version = "0.8.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG rendering library."
documentation = "https://docs.rs/resvg/"
repository = "https://github.com/RazrFalcon/resvg"
readme = "README.md"
categories = ["multimedia::images"]

[workspace]
members = [
    "bindings/resvg-qt",
    "bindings/resvg-skia",
    "bindings/resvg-skia-safe",
    "capi",
    "svgfilters",
    "tools/rendersvg",
    "tools/usvg",
    "usvg",
]

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
log = "0.4"
rgb = "0.8"
usvg = { path = "usvg", version = "0.8", default-features = false }
png = { version = "0.15", default-features = false }
jpeg-decoder = { version = "0.1.15", default-features = false }
svgfilters = { path = "svgfilters", version = "0.1" }

# cairo backend
cairo-rs = { version = "0.8.0", default-features = false, features = ["png"], optional = true }

# qt backend
resvg-qt = { path = "bindings/resvg-qt", version = "0.8", optional = true }

# raqote backend
raqote = { git = "https://github.com/jrmuizel/raqote", rev = "146bd17", default-features = false, optional = true }

# skia backend
resvg-skia = { path = "bindings/resvg-skia", version = "0.8", optional = true }
resvg-skia-safe = { path = "bindings/resvg-skia-safe", version = "0.8", optional = true }

[features]
default = ["text"]
cairo-backend = ["cairo-rs", "png/png-encoding"]
qt-backend = ["resvg-qt"]
raqote-backend = ["raqote"]
skia-backend = ["resvg-skia"]
skia-safe-backend = ["resvg-skia-safe"]
text = ["usvg/text"]

[package.metadata.docs.rs]
# Ignore skia-backend since it cannot be built on docs.rs instance.
features = ["cairo-backend", "qt-backend", "raqote-backend"]

[lib]
doctest = false
