[package]
name = "resvg"
version = "0.7.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG rendering library."
documentation = "https://docs.rs/resvg/"
repository = "https://github.com/RazrFalcon/resvg"
readme = "README.md"
categories = ["multimedia::images"]

[workspace]
members = [
    "capi",
    "tools/rendersvg",
    "tools/usvg",
    "usvg",
    "bindings/resvg-qt",
    "bindings/resvg-skia",
]

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
log = "0.4"
rgb = "0.8"
usvg = { path = "usvg", version = "0.7" }
png = { version = "0.15", default-features = false }
jpeg-decoder = { version = "0.1.15", default-features = false }

# cairo backend
cairo-rs = { version = "0.7.1", default-features = false, features = ["png"], optional = true }

# qt backend
resvg-qt = { path = "bindings/resvg-qt", version = "0.7", optional = true }

# raqote backend
raqote = { version = "0.6.1", default-features = false, optional = true }

# skia backend
resvg-skia = { path = "bindings/resvg-skia", version = "0.7", optional = true }
skia-safe = { version = "0.34.2", optional = true }
skia-bindings = { version = "0.34.2", optional = true }

[features]
cairo-backend = ["cairo-rs"]
qt-backend = ["resvg-qt"]
raqote-backend = ["raqote"]
skia-backend = ["resvg-skia"]
skia-backend-bindings = ["skia-bindings", "skia-safe"]

[package.metadata.docs.rs]
all-features = true

[lib]
doctest = false

[patch.crates-io]
skia-bindings = { git = "https://github.com/StewartCanva/rust-skia", rev = "bef2150f05352a32bf072c52b1718d68974e19fc" }
skia-safe = { git = "https://github.com/StewartCanva/rust-skia", rev = "bef2150f05352a32bf072c52b1718d68974e19fc" }
