[package]
name = "usvg"
version = "0.7.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG simplification library."
categories = ["multimedia::images"]
repository = "https://github.com/RazrFalcon/resvg"
documentation = "https://docs.rs/usvg/"
readme = "README.md"
exclude = ["testing-tools/**"]
workspace = ".."

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
base64 = "0.10"
data-url = "0.1"
harfbuzz_rs = "=1.0"
kurbo = "0.2.3"
libflate = "0.1.25"
log = "0.4"
memmap = "0.7"
rctree = "0.3"
svgdom = { git = "https://github.com/RazrFalcon/svgdom", rev = "f4f4dfe" }
ttf-parser = "0.2"
unicode-bidi = "0.3"
unicode-script = "0.3"
unicode-vo = "0.1"
xmlwriter = { git = "https://github.com/RazrFalcon/xmlwriter", rev = "dac292c" }

[dev-dependencies]
pretty_assertions = "0.6"
