[package]
name = "usvg"
version = "0.8.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG simplification library."
categories = ["multimedia::images"]
repository = "https://github.com/RazrFalcon/resvg"
documentation = "https://docs.rs/usvg/"
readme = "README.md"
exclude = ["testing-tools/**"]
workspace = ".."

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
base64 = "0.11"
data-url = "0.1"
flate2 = { version = "1.0.11", default-features = false, features = ["rust_backend"]}
kurbo = "0.5.6"
log = "0.4"
rctree = "0.3"
xmlwriter = "0.1"

# for svgtree
roxmltree = "0.8"
simplecss = "0.2"
siphasher = "0.2.3"
svgtypes = "0.5"

# for text to path
harfbuzz_rs = { version = "1.0", optional = true }
memmap2 = { git = "https://github.com/RazrFalcon/memmap2-rs", rev = "49e8c1d", optional = true }
ttf-parser = { version = "0.3.0", optional = true }
unicode-bidi = { version = "0.3", optional = true }
unicode-script = { version = "0.3", optional = true }
unicode-vo = { version = "0.1", optional = true }

[features]
default = ["text"]
text = ["harfbuzz_rs", "memmap2", "ttf-parser", "unicode-bidi", "unicode-script", "unicode-vo"]
